development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: mamie_dev
  pool: 5
  username: mamie
  password: mamie
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: mamie_test
  pool: 5
  username: mamie
  password: mamie
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: mamie_prod
  pool: 5
  username: mamie
  password: mamie
